telegram:
  bot:
    token: ${TG_BOT_TOKEN}

bookstack:
  api:
    url: https://bookstack.bassopaolo.com/api
    token: ${BOOKSTACK_TOKEN:}

trello:
  api-key: ${TRELLO_API_KEY}
  token: ${TRELLO_TOKEN}
  board-id: viVw85OK

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/aihelper_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Kent12052@}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Flyway пока выключен — включим потом
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace