telegram:
  bot:
    token: ${TG_BOT_TOKEN}

bookstack:
  api:
    url: https://bookstack.bassopaolo.com/api
    token: токен
# Кредишинолы к Api Trello будут храниться в GitHub Secrets
llm:
  openrouter:
    api-key: ключ
    model: x-ai/grok-4.1-fast
    base-url: https://openrouter.ai/api/v1
    referer: http://localhost:8080/
    title: AI Project Manager